# Nord Theme for Steer
# An arctic, north-bluish clean and elegant theme

name = "Nord"

# Color palette - Nord colors
[palette]
background = "#2e3440"
foreground = "#d8dee9"
black = "#3b4252"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#e5e9f0"
bright_black = "#4c566a"
bright_red = "#bf616a"
bright_green = "#a3be8c"
bright_yellow = "#ebcb8b"
bright_blue = "#81a1c1"
bright_magenta = "#b48ead"
bright_cyan = "#8fbcbb"
bright_white = "#eceff4"
dark_gray = "#3b4252"
gray = "#4c566a"
comment = "#616e88"
# Nord palette
nord0 = "#2e3440"
nord_darker = "#242933"
nord1 = "#3b4252"
nord2 = "#434c5e"
nord3 = "#4c566a"
nord4 = "#d8dee9"
nord5 = "#e5e9f0"
nord6 = "#eceff4"
nord7 = "#8fbcbb"
nord8 = "#88c0d0"
nord9 = "#81a1c1"
nord10 = "#5e81ac"
nord11 = "#bf616a"
nord12 = "#d08770"
nord13 = "#ebcb8b"
nord14 = "#a3be8c"
nord15 = "#b48ead"

# Component styles
[components]
# Status bar
status_bar = { fg = "nord4", bg = "nord1" }

# Input panel
input_panel_border = { fg = "nord3" }
input_panel_border_active = { fg = "nord8" }
input_panel_border_command = { fg = "nord7" }
input_panel_border_approval = { fg = "nord11", bold = true }
input_panel_border_error = { fg = "nord11", bold = true }
input_panel_label = { fg = "nord4" }
input_panel_label_active = { fg = "nord8" }
input_panel_label_command = { fg = "nord7" }
input_panel_label_confirm_exit = { fg = "nord11" }

# Chat list
chat_list_border = { fg = "nord3" }
user_message = { fg = "nord4", bg = "nord_darker" }
user_message_role = { fg = "nord14", bold = true }
user_message_accent = { fg = "nord14" }
assistant_message = { fg = "nord4" }
assistant_message_role = { fg = "nord9", bold = true }
assistant_message_accent = { fg = "nord3" }
system_message = { fg = "comment" }
system_message_role = { fg = "nord13" }
system_message_accent = { fg = "nord3" }

# Tool calls
tool_accent = { fg = "nord3" }
tool_call = { fg = "nord8" }
tool_call_border = { fg = "nord7" }
tool_call_header = { fg = "nord8" }
tool_call_id = { fg = "nord3" }
tool_output = { fg = "nord4" }
tool_success = { fg = "nord14" }
tool_error = { fg = "nord11" }

# Assistant thoughts
thought_box = { fg = "nord3" }
thought_header = { fg = "comment" }
thought_border = { fg = "nord2" }
thought_text = { fg = "comment", italic = true }

# Commands
command_prompt = { fg = "nord14", bold = true }
command_text = { fg = "nord8" }
command_success = { fg = "nord14" }
command_error = { fg = "nord11" }

# General
error_text = { fg = "nord11" }
error_bold = { fg = "nord11", bold = true }
dim_text = { fg = "nord3" }
selection_highlight = { fg = "nord13", bold = true }
placeholder_text = { fg = "nord3", italic = true }

# Model info
model_info = { fg = "nord15" }

# Notices
notice_info = { fg = "nord9" }
notice_warn = { fg = "nord13" }
notice_error = { fg = "nord11" }

# Todo items
todo_high = { fg = "nord11" }
todo_medium = { fg = "nord12" }
todo_low = { fg = "nord14" }
todo_pending = { fg = "nord9" }
todo_in_progress = { fg = "nord13" }
todo_completed = { fg = "nord14" }

# Code editing
code_addition = { fg = "nord14" }
code_deletion = { fg = "nord11" }
code_file_path = { fg = "nord12" }

# Popup
popup_border = { fg = "nord4" }
popup_selection = { fg = "nord6", bg = "nord2" }

# Markdown
markdown_h1 = { fg = "nord8" }
markdown_h2 = { fg = "nord8" }
markdown_h3 = { fg = "nord8" }
markdown_h4 = { fg = "nord9" }
markdown_h5 = { fg = "nord9" }
markdown_h6 = { fg = "nord3" }
markdown_paragraph = { }
markdown_bold = { }
markdown_italic = { }
markdown_strikethrough = { }
markdown_code = { fg = "nord13", bg = "nord1" }
markdown_code_block = { }
markdown_link = { fg = "nord8" }
markdown_blockquote = { fg = "comment" }
markdown_list_bullet = { fg = "nord3" }
markdown_list_number = { fg = "nord9" }
markdown_table_border = { fg = "nord3" }
markdown_table_header = { fg = "nord8", bold = true }
markdown_table_cell = { fg = "nord4" }
markdown_task_checked = { fg = "nord14" }
markdown_task_unchecked = { fg = "nord3" }
# Setup UI
setup_title = { fg = "nord8", bold = true }
setup_border = { fg = "nord3" }
setup_border_active = { fg = "nord8" }
setup_header = { fg = "nord9", bold = true }
setup_text = { fg = "nord4" }
setup_highlight = { bg = "nord2", bold = true }
setup_key_binding = { fg = "nord14", bold = true }
setup_provider_name = { fg = "nord4" }
setup_provider_selected = { bg = "nord2", bold = true }
setup_status_active = { fg = "nord14" }
setup_status_inactive = { fg = "nord11" }
setup_status_in_progress = { fg = "nord13" }
setup_success_icon = { fg = "nord14", bold = true }
setup_error_message = { fg = "nord11" }
setup_hint = { fg = "nord3" }
setup_url = { fg = "nord8", underlined = true }
setup_input_label = { fg = "nord4" }
setup_input_value = { fg = "nord13" }
setup_big_text = { fg = "nord8", bold = true }
